function skillsMember() {
    // Path: member.js
    const skills = [
        {name: "HTML", level: 90},
        {name: "CSS", level: 90},
        {name: "JavaScript", level: 60},
        {name: "PHP", level: 90},
        {name: "MySQL", level: 70},
        {name: "Java", level: 60},
        {name: "C#", level: 60},
        {name: "C", level: 50},
        {name: "Python", level: 40},
        {name: "C++", level: 30},
        {name: "Git", level: 70},
        {name: "Linux", level: 50},
        {name: "NodeJS", level: 40},
        {name: "React", level: 40},
        {name: "Angular", level: 40},
        {name: "Vue", level: 40},
        {name: "MongoDB", level: 40},
        {name: "Docker", level: 40},
        {name: "Kubernetes", level: 40},
        {name: "AWS", level: 40},
        {name: "Azure", level: 40},
        {name: "GCP", level: 40},
        {name: "Kafka", level: 40},
        {name: "GraphQL", level: 40},
        {name: "ElasticSearch", level: 40},
        {name: "Redis", level: 40},
        {name: "RabbitMQ", level: 40},
        {name: "Kibana", level: 40},
        {name: "Logstash", level: 40},
        {name: "Nginx", level: 40},
        {name: "Apache", level: 40},
        {name: "Terraform", level: 40},
        {name: "Ansible", level: 40},
        {name: "Jenkins", level: 40},
        {name: "Bamboo", level: 40},
        {name: "Confluence", level: 40},
        {name: "Jira", level: 40},
        {name: "JFrog", level: 40}
    ];
    return skills;
}